### ISSUE TITLE
Quais os principais marcos (milestones) do projeto?

### ISSUE THREAD

**Issue by masmangan** [agespucrs/susquare#6]
Quais as datas, incidentes (issues) e objetivos dos marcos do projeto?

Sugestão: dividir o tempo até o final do semestre em fatias de mesmo tamanho (por exemplo semanas - time boxed). Criar um marco para cada semana.

**Comment by honscha** [comment]
Bom dia professor Mangan,

Foi criada a seguinte página na wiki do projeto no GitHub:
https://github.com/agespucrs/susquare/wiki/Cronograma-do-projeto
