### ISSUE TITLE
Como são automatizadas tarefas como construção (build), teste e implantação?

### ISSUE THREAD

**Issue by masmangan** [agespucrs/susquare#7]
O projeto adota uma ferramenta para automação de construção e gerência de dependências como Maven? 
Sugestão: localizar e bifurcar (fork) um repositório que utiliza bibliotecas e ferramentas similares como forma de acelerar a configuração do ambiente inicial de desenvolvimento.

Por exemplo, ver:
https://github.com/saigon-devs/docker-mobile

Utilizar esse arquétipo abrevia o esforço de configuração do ambiente e permite reutilizar decisões de projeto.

**Comment by kuquert** [comment]
Estamos em fase de configuração de ferramentas, será abordado na próxima meeting a gerência de dependências.

**Comment by kuquert** [comment]
Conforme [cronograma](https://github.com/agespucrs/susquare/wiki/Cronograma-do-projeto) ficou definido que a integração continua será abordada na Sprint 3.
