### ISSUE TITLE
Como os projetos relacionados são unificados?

### ISSUE THREAD

**Issue by masmangan** [agespucrs/susquare#8]
Seria vantajoso utilizar ramos (branches) no memo repositório para unificar os repositórios susquare-*? Seria vantajoso utilizar várias pastas dentro do mesmo repositório para unificar o controle de mudança?

Sugestão: utilizar o painel Wiki para documentar a relação entre os projetos. Ativar Wiki no painel de configuração de cada projeto.

**Comment by kuquert** [comment]
Discutimos a unificação dos repositórios, mas tendo em vista que vamos trabalhar simultaneamente em várias frentes diferentes optamos por dividir em vários repositórios. Isso facilita também na organização com Waffle e Slack. Utilizaremos o repositório principal para manter uma wiki única. Talvez com a evolução de cada um dos repositórios surja a necessidade de criar uma wiki específica.
